export const TASKS_GET_REQUEST = "TASKS_GET_REQUEST";
export const TASKS_GET_SUCCESS = "TASKS_GET_SUCCESS";
export const TASKS_GET_FAILURE = "TASKS_GET_FAILURE";

export const TASK_UPDATE_REQUEST = "TASK_UPDATE_REQUEST";
export const TASK_UPDATE_SUCCESS = "TASK_UPDATE_SUCCESS";
export const TASK_UPDATE_FAILURE = "TASK_UPDATE_FAILURE";
export const TASK_UPDATE_CLEAR_NOTIFICATION = "TASK_UPDATE_CLEAR_NOTIFICATION";

export const TASK_CREATE_REQUEST = "TASK_CREATE_REQUEST";
export const TASK_CREATE_SUCCESS = "TASK_CREATE_SUCCESS";
export const TASK_CREATE_FAILURE = "TASK_UPDATE_FAILURE";
export const TASK_CREATE_CLEAR_NOTIFICATION = "TASK_CREATE_CLEAR_NOTIFICATION";

export const TASK_DELETE_REQUEST = "TASK_DELETE_REQUEST";
export const TASK_DELETE_SUCCESS = "TASK_DELETE_SUCCESS";
export const TASK_DELETE_FAILURE = "TASK_DELETE_FAILURE";
export const TASK_DELETE_CLEAR_NOTIFICATION = "TASK_DELETE_CLEAR_NOTIFICATION";
