export const TASKS_GET_REQUEST = "TASKS_GET_REQUEST";
export const TASKS_GET_SUCCESS = "TASKS_GET_SUCCESS";
export const TASKS_GET_FAILURE = "TASKS_GET_FAILURE";

export const TASK_UPDATE_REQUEST = "TASK_UPDATE_REQUEST";
export const TASK_UPDATE_SUCCESS = "TASK_UPDATE_SUCCESS";
export const TASK_UPDATE_FAILURE = "TASK_UPDATE_FAILURE";
